services: mongodb
language: node_js
node_js:
  - stable
addons:
  code_climate:
    repo_token:
      secure: "FsamVuWwMOq3MRVRS+NsLQCe4jJaaaDPgF5mOSow5Xm3/MCkb1zyR812IWTSr06I1KhgdA7za8p25vYaG68Vr91c9XoVUdAk2KbGl406wf9AFwooHgh/wVzC2qNhtovGzNpqCc/hipgzDnncT2RKoxg1HcWdgCkToGsNkwjpUavzxnTMwTZra0rhCrjL/ZLzVdpZWkFTsFT5mscgMIDAHWmAxsotNcFDBcTIdnwV0j5TSk2C3B7i2K09B6w3Fe7fD3NuUnB6Ddx8/mfGThN6CJOT1ETXgsqgEyOi489id5J3KOqwcH9fXR6YhE3g1oiHL6X74ZAY5mFE7kYXEZdfF+K1gT158vXkmp34UC/Gngv5gXkIaLDsskrrCtG7tZbj9MCARRlvEZ08YnygCUxiXwb31v7O+PuC94yoZG4YWt726dYg+C1B8cwVbOB7FRN0ugnympIsZBg0e/aY5I2+NS+ko3xv1Y0cWtFm4R1ALDEW2AIXj3LQRuVxRkuMllir0TbIffucfldJYtjWrLOfPWIY6vPBgQ3DsLQh0flhA3B14rvtcuzEyzVoUMNZoKlO2P7g/DX5FJ1+HHpOXQNF78oz7aH2Hu4kqiDEmGCF9rLyBN1mqZHPQzz40YrQjGOL93ZKXFROf6Ag0sRVTJ+mQxrEJgsAY2s2Y+zTjJKOhXc="
script: npm run coverage
before_script:
  - npm install codeclimate-test-reporter -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
